### ISSUE TITLE
想把后续开发的功能改为捐赠可用，不知道大伙能不能接受

### ISSUE THREAD

**Issue by hxh19950701** [hxh19950701/WebViewTvLive#11]
捐赠的人太少了，目前就两个人捐赠。（感谢某华和某子的捐赠，不好意思我这里只能看到你们的最后一个字）
如果大伙能接受，捐赠门槛大概能接受多少？

**Comment by wumingluren** [comment]
刚从吾爱破解那边点击过来。
搞付费使用性质就变了吧。

**Comment by hxh19950701** [comment]
> 刚从吾爱破解那边点击过来。 搞付费使用性质就变了吧。

免费使用，只是存在限制

**Comment by PediyCCDebuger** [comment]
这种要付费才解锁功能的方式个人认为对这个APP来说不太合适。这个APP本质上来说是整合的公共资源，收费的话，容易引起一些不可控的问题。我建议不要做功能限制，可以直接在APP的设置里加一个捐赠界面，这样别人觉得好自然会捐赠。目前你觉得捐赠的人少，是因为你这个APP上并没有这样的捐赠渠道，连作者和源地址都没有，导致传播面非常窄，很多人根本不知道。再说很多人连GitHub是啥网站都不知道，更不可能专门跑这来捐赠。我的看法是把东西做好了，自然有人愿意捐赠。

**Comment by hxh19950701** [comment]
> 这种要付费才解锁功能的方式个人认为对这个APP来说不太合适。这个APP本质上来说是整合的公共资源，收费的话，容易引起一些不可控的问题。我建议不要做功能限制，可以直接在APP的设置里加一个捐赠界面，这样别人觉得好自然会捐赠。目前你觉得捐赠的人少，是因为你这个APP上并没有这样的捐赠渠道，连作者和源地址都没有，导致传播面非常窄，很多人根本不知道。再说很多人连GitHub是啥网站都不知道，更不可能专门跑这来捐赠。我的看法是把东西做好了，自然有人愿意捐赠。

理解！

**Comment by hxh19950701** [comment]
谢谢大家，最终还是决定不做这样的功能。有位网友建议我转战公众号，扩大传播面，用户量大或许可以给这个项目形成正反馈。

**Comment by yeyuyanxin** [comment]
可以接受，就是不知道你这边是否会面临法律风险呢，然后别再开源了。
还有就是想请问盒子如果没有梯子功能是不是就无法更新频道源了？老人没住一起，如果总得去帮忙更新源可能不是很方便。

**Comment by hxh19950701** [comment]
> 可以接受，就是不知道你这边是否会面临法律风险呢，然后别再开源了。 还有就是想请问盒子如果没有梯子功能是不是就无法更新频道源了？老人没住一起，如果总得去帮忙更新源可能不是很方便。

最终还是决定不做捐助可用的功能了
已经有网友建议我给github链接加上代理了，下个版本就会解决此问题，后面还会支持自定义频道源，自己部署，自己维护

**Comment by tangyuan87887** [comment]
期待更加的完善！因为你这个我注册了 github账号！
现在的版本1.2 ，我安装到天猫魔盒上后，打开就没有反应了！不知道是哪里的问题！

**Comment by hxh19950701** [comment]
> 期待更加的完善！因为你这个我注册了 github账号！ 现在的版本1.2 ，我安装到天猫魔盒上后，打开就没有反应了！不知道是哪里的问题！

绝大多数，都是设备WebView的问题。手动安装一下X5内核试试看。
