### ISSUE TITLE
android5.1 android9的机顶盒上都无法在线或者本地安装tbs内核

### ISSUE THREAD

**Issue by rick999999** [hxh19950701/WebViewTvLive#12]
android5.1 android9的机顶盒上都无法在线或者本地安装tbs内核

**Comment by hxh19950701** [comment]
1.2版本行不行

**Comment by rick999999** [comment]
在线内核又可以下载了 无论是1.8beta 还是1.2都可以（建议是否可以提供一个独立的下载链接 ，在github 的release页面下）

但是还是有以下2个bug
1：android5.1 系统花屏
不知道这个怎么可以提供bug报告给你，
2：要点进入调试界面必须在没有全屏出来之前否则在全屏状态 点调试界面直接crash
3：不支持android4.4.4系统
ps：一个小建议
江苏下面可以添加南京的 这些台（很容易抓 没有小尾巴）
http://www.nbs.cn/live/
thx!

**Comment by hxh19950701** [comment]
你的5.1系统的设备能不能运行“电视浏览器”？如果没有问题，我再看看

**Comment by hxh19950701** [comment]
> 在线内核又可以下载了 无论是1.8beta 还是1.2都可以（建议是否可以提供一个独立的下载链接 ，在github 的release页面下）
> 
> 但是还是有以下2个bug 1：android5.1 系统花屏 不知道这个怎么可以提供bug报告给你， 2：要点进入调试界面必须在没有全屏出来之前否则在全屏状态 点调试界面直接crash 3：不支持android4.4.4系统 ps：一个小建议 江苏下面可以添加南京的 这些台（很容易抓 没有小尾巴） http://www.nbs.cn/live/ thx!

南京台，我不太会抓源，你抓好发给我

**Comment by rick999999** [comment]
> 你的5.1系统的设备能不能运行“电视浏览器”？如果没有问题，我再看看
你看看能否添加一个disable 硬件加速的选项？

**Comment by hxh19950701** [comment]
你的5.1系统的设备能不能运行“电视浏览器”？
然后浏览器播放本来就比较吃性能的，软解基本用不了

**Comment by hxh19950701** [comment]
其实我也有个5.1的盒子，小米盒子3增强版。也是苦于一直运行不了这个app，无论是升级webview，装x5，开软解，都不行。
其实根本就是厂家的问题，电视上的webview基本没有app用，也不带浏览器，厂家懒得测试

**Comment by rick999999** [comment]
> 其实我也有个5.1的盒子，小米盒子3增强版。也是苦于一直运行不了这个app，无论是升级webview，装x5，开软解，都不行。 其实根本就是厂家的问题，电视上的webview基本没有app用，也不带浏览器，厂家懒得测试

你说的没错 厂家不适配新版的webview 所以我碰到 都是单独装chrome去看视频
原本以为tbs内核是不是有所不同没想到


但是你是否可以测试一下 在你5.1的盒子测试一下 关掉硬件加速 看看是否可以解决花屏的问题？

**Comment by hxh19950701** [comment]
> > 其实我也有个5.1的盒子，小米盒子3增强版。也是苦于一直运行不了这个app，无论是升级webview，装x5，开软解，都不行。 其实根本就是厂家的问题，电视上的webview基本没有app用，也不带浏览器，厂家懒得测试
> 
> 你说的没错 厂家不适配新版的webview 所以我碰到 都是单独装chrome去看视频 原本以为tbs内核是不是有所不同没想到
> 
> 但是你是否可以测试一下 在你5.1的盒子测试一下 关掉硬件加速 看看是否可以解决花屏的问题？

上面说了，开软解，都不行（即 关掉硬件加速）
