### ISSUE TITLE
河南地方台

### ISSUE THREAD

**Issue by via2009** [hxh19950701/WebViewTvLive#14]
https://static.hntv.tv/kds/

帮忙给添加到频道列表吧

**Comment by hxh19950701** [comment]
没法通过url直接访问频道，只能看河南卫视，而河南卫视已经有了

**Comment by miaomiaosoft** [comment]
像这种台目前只能依靠解析代理。

@hxh19950701 从源码里我发现全屏逻辑应该是用注入JS脚本实现的，但其实这个功能也可以开放给用户，像油猴那样。
比如我可以自己写脚本实现当浏览地址为 a.com/live 并加载渲染完成后自动点击全屏/播放按钮或任意元素，或者脚本解析出M3U8直播源后跳转播放，或许可以减轻你在适配直播源上的工作量。

这个台需要先手动点击播放按钮才能播放：https://glive.habctv.com/tv/803?uin=1610
为此昨天尝试用CHATGPT写了个油猴脚本自动点击发现是可行的：

// ==UserScript==
// @name         延迟点击视频播放按钮
// @namespace    http://tampermonkey.net/
// @version      0.1
// @description  当网页加载并渲染完成后，延迟一秒点击视频播放按钮
// @author       You
// @match        *://*/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';

    // 页面完全加载并渲染完成
    window.addEventListener('load', function() {
        // 等待1秒
        setTimeout(function() {
            // 获取视频播放按钮元素
            const playButton = document.getElementById('video-action-play');
            if (playButton) {
                // 点击播放按钮
                playButton.click();
            } else {
                console.log('未找到视频播放按钮');
            }
        }, 1000); // 延迟1秒（1000毫秒）
    });
})();

**Comment by hxh19950701** [comment]
正在做了，下个版本支持！
