### ISSUE TITLE
提一个小建议。

### ISSUE THREAD

**Issue by liujindongde** [hxh19950701/WebViewTvLive#16]
首先非常感谢您的贡献。
使用时真的非常棒，但是有一点小小的建议，不知道是否能实现。
现在换台的时候，会看到先弹出网页，然后最大化播放，每次换台都弹出一次网页，使用体验上有点乱乱的感觉，不知道能否在换台时，直接黑屏隐蔽掉网页，等视频最大化后再显示画面，或者换台时继续播放当前节目画面，待新的频道最大化后再切换过去，这样在电视端的使用感受更加流畅。
如果我的建议对您的工作量或者成本造成影响，请您谅解，我收回意见。
最后再次感谢您的贡献。

**Comment by hxh19950701** [comment]
黑屏时间会比较久，体验不怎么好。当然如果你有更好的办法，欢迎告知

**Comment by miaomiaosoft** [comment]
@hxh19950701 我曾经也提过这个建议，不过在我修改旧版本开启加载图片功能后，感觉就没有必要了，因为有了图片加载网页时就显得很正常顺眼，禁用图片会到处变成破图或影响页面元素的位置结构观感不好，那样就真的不美观不如黑屏。
另外，开启加载图片后我才发现之前播放视频时会出现的白色小圆点其实是个播放图标。

**Comment by tangyuan87887** [comment]
版主，1.8版本，手动点击过切换播放源  1  和 2  后，系统总是在自己在 源  1  和  2  之间切换。

**Comment by javadodobird** [comment]
可以在设置做一个可选择项目？

1，不加载网页图片（加载速度快）
2，前景黑屏（背景作业，不加载网页图片）
3，加载网页图片（加载速度慢）

让使用者自己决定用哪一个？

**Comment by javadodobird** [comment]
> 黑屏时间会比较久，体验不怎么好。当然如果你有更好的办法，欢迎告知

可以在设置做一个可选择项目？

1 • 前景加载网页，前景不加载网页图片
2 • 前景显示黑屏，背景加载网页，背景不加载网页图片
3 • 前景加载网页，前景加载网页图片

让使用者自己决定用哪一个？

**Comment by hxh19950701** [comment]
这个功能只是美观问题，尚不紧要。目前这个app还有很多基础功能未实现（主页提到的），我现在更希望将有限的开发精力投入到更主要的功能上。
