### ISSUE TITLE
在低端盒子最长加载时间30秒不夠用

### ISSUE THREAD

**Issue by javadodobird** [hxh19950701/WebViewTvLive#17]
作者你好，
最长加载时间30秒不夠用，
在低端盒子看yangshipin地址用了30秒还没有加载完成就又再次重新加载，再次用了30秒还没有加载完成就又再次重新加载，形成了一个死循环，
最长加载时间可否增加45秒，60秒，90秒，120秒等的选项？
谢谢！

**Comment by hxh19950701** [comment]
你盒子是有多低端。。。。

**Comment by javadodobird** [comment]
> 你盒子是有多低端。。。。

主板：amlogic P281
CPU：4核心 ARM Cortex-A53 @ 1200 MHz
GPU：ARM Mali-450 MP

**Comment by zbby1987** [comment]
> > 你盒子是有多低端。。。。
> 
> 主板：amlogic P281 CPU：4核心 ARM Cortex-A53 @ 1200 MHz GPU：ARM Mali-450 MP

这配置不低端，就是网速慢

**Comment by hxh19950701** [comment]
升级1.9.1
