### ISSUE TITLE
方便让老年人使用者可以按遥控器下键跨分类换频道

### ISSUE THREAD

**Issue by javadodobird** [hxh19950701/WebViewTvLive#18]
作者你好，
可否加一个选项，方便让老年人使用者可以按遥控器下键跨分类换频道，
老年人想要遥控器从CNTN Documentary换频道到北京卫视，
在央视分类最后一个频道30 CGTN Documentary，按遥控器下键换下一个频道会是央视分类01 CCTV-1综合，属于是分类内内循环换频道的逻辑，
因为老年人不懂央视分类，卫视分类，湖南分类等等的分类逻辑，只懂按遥控器上键，下键，0键，1键，2键，……7键，8键，9键，
所以会在央视分类最后一个频道30 CGTN Documentary时，按遥控器下键换下一个频道，不能去到卫视分类的01 北京卫视频道，
可否加一个选项，方便让老年人使用者可以按遥控器下键跨分类换频道，
谢谢！

**Comment by hxh19950701** [comment]
老年人使用，不建议使用过于繁多的频道列表。
使用“央视+卫视”单列表即可解决你的问题。

**Comment by javadodobird** [comment]
> 老年人使用，不建议使用过于繁多的频道列表。 使用“央视+卫视”单列表即可解决你的问题。

烦请作者可以加入"央视+卫视"单列表的选项？谢谢了！

**Comment by hxh19950701** [comment]
> > 老年人使用，不建议使用过于繁多的频道列表。 使用“央视+卫视”单列表即可解决你的问题。
> 
> 烦请作者可以加入"央视+卫视"单列表的选项？谢谢了！

已经有了，设置界面多看看

**Comment by javadodobird** [comment]
> > > 老年人使用，不建议使用过于繁多的频道列表。 使用“央视+卫视”单列表即可解决你的问题。
> > 
> > 
> > 烦请作者可以加入"央视+卫视"单列表的选项？谢谢了！
> 
> 已经有了，设置界面多看看

抱歉抱歉，
没有留意到作者github的Code三天前发布了1.8(Beta)的新版本，
请多多包涵，
谢谢！
