### ISSUE TITLE
把所有分类全部频道串成一个圆圈循环，仅用遥控器上键，或者下键，便可以走完整个圆圈循环

### ISSUE THREAD

**Issue by javadodobird** [hxh19950701/WebViewTvLive#19]
你好作者，

在每个分类第一个频道，按遥控器上键换频道，可以换到前一个分类最后一个频道，

在每个分类最后一个频道，按遥控器下键换频道，可以换到后一个分类第一个频道，

就是说，在设置里有两个可选择选项，一个选项是，把所有分类全部频道串成一个圆圈循环，仅用遥控器上键，或者下键，便可以走完整个圆圈循环，

另一个选项是仅在分类内内循环换频道，换频道不会换去前一个分类或者后一个分类的频道，

谢谢！

**Comment by hxh19950701** [comment]
此功能确定不会做

**Comment by javadodobird** [comment]
> 此功能确定不会做

烦请可否发私人讯息告知原因？

**Comment by hxh19950701** [comment]
作者个人的喜好问题

**Comment by javadodobird** [comment]
> 作者个人的喜好问题

喔，好的
