### ISSUE TITLE
遥控器无法浏览列表

### ISSUE THREAD

**Issue by etern** [hxh19950701/WebViewTvLive#2]
按遥控器确认键，左侧弹出频道列表。再按上下键，无响应。

期望：在频道列表，按上下键能浏览频道

海信电视android6.0(api23), x5:46284

**Comment by hxh19950701** [comment]
列表有没有光标

**Comment by etern** [comment]
列表没有光标。
而且左右键切 海外/央视 是有效的。
就上下键无效。

**Comment by hxh19950701** [comment]
测试了几次，复现概率怎么样

**Comment by etern** [comment]
测试了很多次。开始用1.0版本，必现。
刚更新了1.1版本，也是必现。
电视关了重开也没用。

**Comment by hxh19950701** [comment]
估计是RecyclerView无法获取到焦点导致的，你看看其他界面：如退出确认界面，设置界面，可以出现光标吗？如果有图片，视频更好

**Comment by etern** [comment]
都没有光标

Uploading video_20241001_114354_edit.mp4…

**Comment by etern** [comment]
没有光标

https://github.com/user-attachments/assets/5d956c25-4293-4d80-a758-c1ee65623e92

**Comment by hxh19950701** [comment]
好的，我有时间看一下此问题

**Comment by hxh19950701** [comment]
测试一下1.2版本
