### ISSUE TITLE
大湾区卫视不能播放

### ISSUE THREAD

**Issue by uairyu** [hxh19950701/WebViewTvLive#20]
电脑尝试切换手机ua使用手机版网页，同样也不行，希望使用pc版解析视频

**Comment by hxh19950701** [comment]
> 电脑尝试切换手机ua使用手机版网页，同样也不行，希望使用pc版解析视频

收到！

**Comment by hxh19950701** [comment]
确定一下：PC版网页是更稳定的吗？

**Comment by uairyu** [comment]
> 确定一下：PC版网页是更稳定的吗？

这个我也不敢说，但这个是官网，我挂一段时间pc版网页看看？

**Comment by uairyu** [comment]
看起来应该是没问题的，连续播了一个小时没卡顿过，就是进度条直播播放时间不知道为什么不到10分钟，可能会中间重新自动刷新一下什么的？

**Comment by hxh19950701** [comment]
我下个版本将手机版和PC版都加进去吧，作为两个源

**Comment by hxh19950701** [comment]
现在gdtv.com的全播放不了。。。

**Comment by uairyu** [comment]
> 现在gdtv.com的全播放不了。。。

你是不是去错网站了，应该是荔枝网 www.gdtv.cn 这个吧，不是.com

**Comment by hxh19950701** [comment]
> > 现在gdtv.com的全播放不了。。。
> 
> 你是不是去错网站了，应该是荔枝网 [www.gdtv.cn](http://www.gdtv.cn) 这个吧，不是.com

说错了，就是gdtv.cn，你那还能加载视频吗？

**Comment by uairyu** [comment]
![image](https://github.com/user-attachments/assets/3255d4da-ab41-4491-9391-9b97ed79d90d)
可以

**Comment by hxh19950701** [comment]
用webviewtv打开

**Comment by hxh19950701** [comment]
> 用webviewtv打开

webviewtv现在无论是手机版还是PC版都加载不了视频

**Comment by uairyu** [comment]
> > 用webviewtv打开
> 
> webviewtv现在无论是手机版还是PC版都加载不了视频

可是我现在的1.8版本他打开的还是手机版网页，你电脑打开荔枝网也不播放不了吗？webviewtv的要不你发个新包我试试？

**Comment by hxh19950701** [comment]
> > > 用webviewtv打开
> > 
> > 
> > webviewtv现在无论是手机版还是PC版都加载不了视频
> 
> 可是我现在的1.8版本他打开的还是手机版网页，你电脑打开荔枝网也不播放不了吗？webviewtv的要不你发个新包我试试？

右下角打开原网页

**Comment by uairyu** [comment]
> > > > 用webviewtv打开
> > > 
> > > 
> > > webviewtv现在无论是手机版还是PC版都加载不了视频
> > 
> > 
> > 可是我现在的1.8版本他打开的还是手机版网页，你电脑打开荔枝网也不播放不了吗？webviewtv的要不你发个新包我试试？
> 
> 右下角打开原网页

就是打开原网页会跳到 m.gdtv.cn 手机版网页，我用电脑浏览器进手机版网页同样也播放不了

**Comment by hxh19950701** [comment]
试了各种方法都不行。。
最后改了一下WebViewTV的包名，就可以加载了。。。
看来是用的人太多，被针对了。。

**Comment by uairyu** [comment]
> 试了各种方法都不行。。 最后改了一下WebViewTV的包名，就可以加载了。。。 看来是用的人太多，被针对了。。

但按理说你请求这个网页，哪一步会发送apk包名出去？这太怪了吧，那改完之后手机版网页也能正常加载出视频吗？我这边依然手机版网页加载不出东西

**Comment by hxh19950701** [comment]
> > 试了各种方法都不行。。 最后改了一下WebViewTV的包名，就可以加载了。。。 看来是用的人太多，被针对了。。
> 
> 但按理说你请求这个网页，哪一步会发送apk包名出去？这太怪了吧，那改完之后手机版网页也能正常加载出视频吗？我这边依然手机版网页加载不出东西

貌似js是可以读到当前apk的包名的？我不太懂前端的知识，但是的确把包名改了，就可以加载，改回去，就加载不了了

**Comment by uairyu** [comment]
难道腾讯的x5内核在搞事？那大佬能不能做到类似面具那种随机生成新包名再重新安装这种操作？

**Comment by hxh19950701** [comment]
试了一中午，基本可以肯定了。。。包名中只要出现webviewtv，100%无法加载。。。把TBS SDK完全剔除也无济于事。
目前还不知道网站是如何知道应用程序包名的，但可以肯定的是已经有电视台知道这个app的存在了。

**Comment by uairyu** [comment]
> 试了一中午，基本可以肯定了。。。包名中只要出现webviewtv，100%无法加载。。。把TBS SDK完全剔除也无济于事。 目前还不知道网站是如何知道应用程序包名的，但可以肯定的是已经有电视台知道这个app的存在了。

惨，辛苦大佬测试了，那，打算怎么解决荔枝网这个呢。。

**Comment by hxh19950701** [comment]
> 惨，辛苦大佬测试了，那，打算怎么解决荔枝网这个呢。。

最简单的方法就是换个包名。。

**Comment by uairyu** [comment]
> > 惨，辛苦大佬测试了，那，打算怎么解决荔枝网这个呢。。
> 
> 最简单的方法就是换个包名。。

这个也只是缓兵之计吧

**Comment by hxh19950701** [comment]
> 这个也只是缓兵之计吧

那没办法啊，先看看呗。我一个人也没时间仔细研究这个。
万一把电视台弄急了，直接加个人机验证，我就只能干瞪眼了

**Comment by javadodobird** [comment]
> > 这个也只是缓兵之计吧
> 
> 那没办法啊，先看看呗。我一个人也没时间仔细研究这个。 万一把电视台弄急了，直接加个人机验证，我就只能干瞪眼了

貌似广东荔枝网工作人员有所察觉，采取了反制措施行动，
现在用WebView电视已经看不到荔枝网频道，
用谷歌chrome浏览器可以正常看到荔枝网频道

**Comment by miaomiaosoft** [comment]
简单查了下，网站应该没办法获取包名。
既然改包名可以恢复，那可能和包名类似的 Device-Id 等固定参数有关，修改包名可能影响这类参数。
![image](https://github.com/user-attachments/assets/e9c775d4-917f-4d0b-bbe2-e300d05e421e)

**Comment by Wings168** [comment]
手机微信和浏览器打开网站都能直接看，但是使用app就是不行，估计还是监控了某些参数进行精准拒绝
