### ISSUE TITLE
下载地址能不能换个别家的网盘？

### ISSUE THREAD

**Issue by 8u8m** [hxh19950701/WebViewTvLive#24]
城通盘的限速太厉害了，只有几十K每秒
建议用蓝奏盘，或者123盘也行
github这里下载不了apk文件
zip包下载了不知道怎么安装

**Comment by hxh19950701** [comment]
5M的文件，其实就算是30K/s，也不需要花费多久就能够下载完。
其实最主要的是他可以返利给作者，白嫖的用户太多了，理解一下。
