### ISSUE TITLE
安装了内核依然不支持视频播放

### ISSUE THREAD

**Issue by andysun2046** [hxh19950701/WebViewTvLive#26]
安装了内核，依然提示当前的浏览器不支持视频播放，请升级浏览器或更换设备，若为360 [QQ或搜狗浏览器，需使用极速模式。求指导。
![IMG_20241202_124500](https://github.com/user-attachments/assets/0d591501-474c-4d4a-a6ca-65413e9a42b5)

**Comment by hxh19950701** [comment]
实在不行，就花个几十块钱买个电视盒子吧。
