### ISSUE TITLE
小米盒子3增强版安装X5核心就闪退什么情况？

### ISSUE THREAD

**Issue by 389377616** [hxh19950701/WebViewTvLive#29]
软件安装上直接播放页没办法播放，页面进度100%一行就卡在哪里没反应，我装上X5核心发现播放页面进度一跑满100%软件就会直接闪退.这个是啥情况？系统太老还是啥情况
![微信图片_20241209120447](https://github.com/user-attachments/assets/93342b2f-1519-4b7f-943a-bf1c3944ac4c)

**Comment by hxh19950701** [comment]
换设备

**Comment by 389377616** [comment]
> 换设备

这个什么情况?设备太老了嘛，这个是对系统版本有要求嘛

**Comment by hxh19950701** [comment]
> > 换设备
> 
> 这个什么情况?设备太老了嘛，这个是对系统版本有要求嘛

https://github.com/hxh19950701/WebViewTvLive/issues/12#issuecomment-2480606935
