### ISSUE TITLE
无法全屏

### ISSUE THREAD

**Issue by virusmaster** [hxh19950701/WebViewTvLive#33]
安装在盒子上，播放到电视上只显示小窗口无法全屏。
按照“一般是设备 WebView 的问题，待X5内核下载完成，重启 App 即可。若无法自动下载X5内核，请在设置-TBS调试界面内选择“安装线上内核”来手动安装。” 也无法解决。
另外一个问题就是，进入调试界面后，遥控器选择项目按钮看不到按钮变色，不知道定位在哪，所以要定位到"debugX5‘’非常困难。
能默认开启X5内核吗？
谢谢！

**Comment by virusmaster** [comment]
昨晚按照公众号上的方法，进入调试界面按两下向右，安装了线上内核，重启了。 可仍然无法全屏。安卓9。

**Comment by hxh19950701** [comment]
提供机器型号

**Comment by virusmaster** [comment]
**魔百盒M401A**，还有一个好像是411，还没试。  如果能默认解决全屏就完美了。

**Comment by hxh19950701** [comment]
我手上没有这个设备

**Comment by hxh19950701** [comment]
来这里反馈一下：https://github.com/hxh19950701/WebViewTvLive/issues/34

**Comment by hxh19950701** [comment]
有人用刷其他刷机包的方式解决了这个问题，你看是不是也可以尝试一下这个方式
