### ISSUE TITLE
换台体验优化

### ISSUE THREAD

**Issue by QiJinDeBaiBaoXiang** [hxh19950701/WebViewTvLive#39]
作者您好，家里目前使用的电视系统是安卓5.1，处理器是个arm32位的四核不知名处理器，system webview已经更到目前能跟更新的95点几，换台还是需要15秒以上，体验很差，还希望作者能优化下换台性能，换台过程增加个动画或者遮罩不要显得很突兀，谢谢了

**Comment by hxh19950701** [comment]
很抱歉，这个作者无力优化。
造成这个问题的主要原因还是由于您设备性能的不足，加载PC端网页需要消耗大量性能。
您可去“设置”内打开无图模式，或许可以获取一点性能提升。
此外，“WebView 电视”的工作原理注定了它的换台过程需要比较长的时间，您也可以换用其他同类软件来达到您的目的。
