### ISSUE TITLE
央视数字vip

### ISSUE THREAD

**Issue by gstory0404** [hxh19950701/WebViewTvLive#41]
央视数字下的频道都是vip，是否可以影藏这个类目

**Comment by hxh19950701** [comment]
https://github.com/hxh19950701/WebViewTvLive/issues/35

**Comment by hxh19950701** [comment]
因为央视频偶尔会把这些频道变成限免，偶尔有用户需要看这些频道，因此还是决定保留了这些收费频道。

**Comment by gstory0404** [comment]
@hxh19950701 好的，感谢回复
