### ISSUE TITLE
可以加一些上海的频道么？

### ISSUE THREAD

**Issue by davinma** [hxh19950701/WebViewTvLive#5]
家里老人不熟悉操作，能不能加上海的相关频道：
https://live.kankanews.com/huikan

**Comment by hxh19950701** [comment]
可以，不过我需要你给我提供稳定的播放源。
东方卫视当前已经收录了。

**Comment by hxh19950701** [comment]
你给的网址虽然有很多频道，但是无法使用URL直接跳转。

**Comment by davinma** [comment]
试了下，浏览器调试工具切换到移动设备，再刷新网页，每个频道在 URL 中会对应一个 id，比如：

> https://live.kankanews.com/huikan?id=2

`id=2` 对应的是新闻综合频道，此时再切回桌面模式，URL 里的 id 依旧不会丢失，且切换成对应的频道了。后面只需要改 id 就能得到所有的频道了。算是钻了个空子😄

**Comment by hxh19950701** [comment]
已收录至完整列表，刷新频道列表即可。
