### ISSUE TITLE
【广电免费电视作者在线提bug】提一下 播放js重定向视频链接和吉林卫视全屏问题

### ISSUE THREAD

**Issue by wzsvip** [hxh19950701/WebViewTvLive#7]
1. 吉林卫视 [在电视频道分类], 能访问网页, 获取不到全屏    https://www.jlntv.cn/tv?id=104
log的id     7ace53c0e2b449e08e4a9a002c132061
2. 能访问黑屏, 不会跳转到视频页面, 代码是 js 重定向的, 浏览器正确播放
吉林地方台 [吉林分类中]   https://hls.wztv.us.kg/jilintv.html?id=jlggxw
3. 能访问黑屏, 重庆新闻在[电视频道里面]   https://sj.cbg.cn/wap/list/4918/1.html

订阅整理链接
https://9361.kstore.space/playlist.json

**Comment by hxh19950701** [comment]
1. 吉林卫视需要点击播放按钮后，才会加载video标签，待我有时间适配一下
2. 2和3都是跳转问题，我有空研究一下

**Comment by hxh19950701** [comment]
广电免费电视，这个app是你做的吗？

**Comment by tangyuan87887** [comment]
版主，咨询个问题，天猫魔盒M18安装后，打开后只是显示页面，不会播放节目和全屏，是因为没有自动下载X5 WebView 的原因吗？

**Comment by tangyuan87887** [comment]
还有，能再增加一个频道吗？？央视和卫视  ，现在只有 央视和湖南的。

**Comment by hxh19950701** [comment]
> 还有，能再增加一个频道吗？？央视和卫视 ，现在只有 央视和湖南的。

等2.0版吧，会支持自定义频道列表

**Comment by miaomiaosoft** [comment]
@hxh19950701 上面说的 https://hls.wztv.us.kg/jilintv.html?id=jlggxw 不能跳转可能和你默认禁止重定向有关，我修改1.2版本允许重定向后是可以正常播放的。
其实也没有必要禁止重定向，不然有些像这种代理解析式的链接会无法播放。

**Comment by hxh19950701** [comment]
> @hxh19950701 上面说的 https://hls.wztv.us.kg/jilintv.html?id=jlggxw 不能跳转可能和你默认禁止重定向有关，我修改1.2版本允许重定向后是可以正常播放的。 其实也没有必要禁止重定向，不然有些像这种代理解析式的链接会无法播放，CF的人机验证似乎也会失败。

打开了有没有遇到什么异常，没有异常我下版本就打开吧

**Comment by miaomiaosoft** [comment]
@hxh19950701 巧了，正要补充，目前发现，禁用重定向时https://m.douyu.com/8896151 斗鱼轮播可以正常保持移动端看，
允许重定向后会跳转到 https://www.douyu.com/8896151，PC模式就没移动端简洁了且全屏也有问题。

我在电脑上在chrome开发者工具中切换到移动端模式访问 https://m.douyu.com/8896151 是不会跳转的。
用webtv访问https://www.browserscan.net/zh/user-agent 查了下UA发现居然是win10
感觉会跳转到PC端和UA有关。

建议弄两个设置，一个重定向开关，一个选择不同平台UA。

**Comment by hxh19950701** [comment]
> @hxh19950701 巧了，正要补充，目前发现，禁用重定向时 https://m.douyu.com/8896151 斗鱼轮播可以正常保持移动端看， 允许重定向后会跳转到 https://www.douyu.com/8896151 ，PC模式就没移动端简洁了且全屏也有问题。
> 
> 我在电脑上在chrome开发者工具中切换到移动端模式访问 https://m.douyu.com/8896151 是不会跳转的。 用webtv访问https://www.browserscan.net/zh/user-agent 查了下UA发现居然是win10 感觉会跳转到PC端和UA有关。
> 
> 建议弄两个设置，一个重定向开关，一个选择不同平台UA。

默认就是win10的ua，当初发现太多网站发现你是手机UA就跳app下载界面了，而且任由网页这么跳来跳去，适配也很麻烦，索性先禁止跳转了。
你的问题，增加一个webpageadapter就可以适配了

**Comment by fire7708** [comment]
魔百盒机顶盒打开不能自动全屏。
TBS调试界面内已经选择安装线上内核，并且提示重启。现在还是没有解决这个问题
