### ISSUE TITLE
果然，我还是高估了这个世界的善良

### ISSUE THREAD

**Issue by hxh19950701** [hxh19950701/WebViewTvLive#8]
起初写这个App，是因为去年电视家倒闭，刚好我年底失业，利用年前空闲时间写的。年后找到工作后，我也花了不少时间在维护这个项目上，迭代了大半年，才使得App变成现在比较好用的状态。
2024年国庆前，本着独乐乐不如众乐乐的精神，我将App开源。想着能聚集来源社区的力量，能将App变得更好用，同时能接收到善良人士的捐赠，使我更积极的维护这个项目。
现在，一个月过去了，我所期待的事情并没有发生，我没有想到的事情却发生了。那就是，有人将我的App重打包赚钱。
从我的后台数据显示来看，仅仅过了几天，盗版app的安装量就是我的十倍多了。
我现在正在考虑是否停止开源，甚至停止维护此项目。我花了不少精力在这个项目上，没有一分钱收益，那些盗版作者，仅仅是重新打包一下，就可以坐享其成。
这件事情对我的打击很大，还好现在这个App还不是特别好用，早日退出，对我也好。

**Comment by miaomiaosoft** [comment]
还是希望能继续开发，可以采取一些防盗版措施，比如启动时显示盗版提示。

**Comment by sunyis** [comment]
很多应用都是, 不开源, 然后360加固, 这都有人卖, 环境真差

**Comment by linxbin** [comment]
这个世界就是这样，杀人放火金腰带，修桥补路无尸骸

**Comment by rs5173** [comment]
国内很多人都缺钱买药买棺材，建议闭源加固，以后直接发布apk

**Comment by hxh19950701** [comment]
盗版App之一：https://github.com/Eanya-Tonic/CCTV_Viewer/issues/110
改了app名字，还换了一个比较low的图标，没有注明来源作者，有没有拿去赚钱我还不知道。

**Comment by zbby1987** [comment]
> 很多应用都是, 不开源, 然后360加固, 这都有人卖, 环境真差

即使加固了，他们也能脱裤子。。。这波人里有脱裤子高手

**Comment by zbby1987** [comment]
> 盗版App之一：[Eanya-Tonic/CCTV_Viewer#110](https://github.com/Eanya-Tonic/CCTV_Viewer/issues/110) 改了app名字，还换了一个比较low的图标，没有注明来源作者，有没有拿去赚钱我还不知道。

你和电视浏览器的作者，基本都是因为电视家不能看了以后，同时间使用了类似的处理方法做了浏览器模式的app。他是那会儿刚毕业。。。

**Comment by zbby1987** [comment]
> 盗版App之一：[Eanya-Tonic/CCTV_Viewer#110](https://github.com/Eanya-Tonic/CCTV_Viewer/issues/110) 改了app名字，还换了一个比较low的图标，没有注明来源作者，有没有拿去赚钱我还不知道。

那个叫保全的，开源行业公敌。。。

**Comment by hxh19950701** [comment]
> > 盗版App之一：[Eanya-Tonic/CCTV_Viewer#110](https://github.com/Eanya-Tonic/CCTV_Viewer/issues/110) 改了app名字，还换了一个比较low的图标，没有注明来源作者，有没有拿去赚钱我还不知道。
> 
> 你和电视浏览器的作者，基本都是因为电视家不能看了以后，同时间使用了类似的处理方法做了浏览器模式的app。他是那会儿刚毕业。。。

我说的是那个广电免费电视

**Comment by zbby1987** [comment]
我知道你说的广电的那个，
我就是介绍一下这个项目的作者，指不定你们俩能合作出来个更牛的类似于tvbox的浏览器壳工具



---原始邮件---
发件人: "Vasthread ***@***.***&gt;
发送时间: 2024年11月6日(周三) 晚上6:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [hxh19950701/WebViewTvLive] 果然，我还是高估了这个世界的善良 (Issue #8)




   
盗版App之一：Eanya-Tonic/CCTV_Viewer#110 改了app名字，还换了一个比较low的图标，没有注明来源作者，有没有拿去赚钱我还不知道。
  
你和电视浏览器的作者，基本都是因为电视家不能看了以后，同时间使用了类似的处理方法做了浏览器模式的app。他是那会儿刚毕业。。。
  
我说的是那个广电免费电视

**Comment by Easonies** [comment]
那些重新打包再去卖软件的人我在某音见一个举报一个，建议作者加上防伪的标记，再是可以考虑能否实现安装标记类似SN码的功能，亦或是改为单码或邀请码注册制，金蝉子所想而非现实之所见。希望作者能够继续维护项目，添加版权保护。

**Comment by hxh19950701** [comment]
> 那些重新打包再去卖软件的人我在某音见一个举报一个，建议作者加上防伪的标记，再是可以考虑能否实现安装标记类似SN码的功能，亦或是改为单码或邀请码注册制，金蝉子所想而非现实之所见。希望作者能够继续维护项目，添加版权保护。

谢谢！像你所说的这些功能我很难实现，我写app不是为了赚钱，我有工作，不以此为生。写这个app也只是想着在电视家关闭后能有个看电视的软件，让家中的电视机不用吃灰，让父母有个简单的方式使用智能电视。
项目我应该还是会维护，但是不会开源了。

**Comment by bhuangzhe** [comment]
很遗憾听到这个消息，据我所知，这种行为几乎已经是个完整的灰色产业链，有人专门在github上打包开源软件拿去卖！钻漏洞的坏人无所不在，但是软件初衷还是为老人而设计，初衷不改，功德无量，但建议还是别开源了

**Comment by suweiteng** [comment]
今日发现这个软件，感叹从官网播放video的创意，惊为天人。一番搜索，来到此地。希望软件不开源，直播源url能定义(想添加一些地方台)

**Comment by dushez** [comment]
提供几个思路：
1、将版权信息文件加密，调用版权文件验证hash。
2、app运行时检查版权信息是否被修改，如果不对在app上提示，此文件也加密。
3、建一个个人公众号，添加到版权信息里，让一些连giyhub都打不开的用户可以找到你。然后用公众号更新，圈粉。用公众号让你产生一点收入，这也算是一种正向反馈。

**Comment by hxh19950701** [comment]
> 提供几个思路： 1、将版权信息文件加密，调用版权文件验证hash。 2、app运行时检查版权信息是否被修改，如果不对在app上提示，此文件也加密。 3、建一个个人公众号，添加到版权信息里，让一些连giyhub都打不开的用户可以找到你。然后用公众号更新，圈粉。用公众号让你产生一点收入，这也算是一种正向反馈。


谢谢你提供的思路！
的确像这样的app上应用市场加广告都不太现实，仅靠用户微薄的打赏也不大可能支撑得下去。

**Comment by javadodobird** [comment]
坚决支持作者不要再开源这个软件，

给那些无道德底线的偷竊者王八蛋增加偷竊的难度！

**Comment by JohnWayneHong** [comment]
可惜了，今天还想学习Android TV开发的...

**Comment by hxh19950701** [comment]
> 可惜了，今天还想学习Android TV开发的...

老版本的源码还在，可以学习

**Comment by gdtool** [comment]
开源环境很恶劣,尤其是china
我建议不要开源 作者能免费给我们用就已经很好了

**Comment by hxh19950701** [comment]
> 提供几个思路： 1、将版权信息文件加密，调用版权文件验证hash。 2、app运行时检查版权信息是否被修改，如果不对在app上提示，此文件也加密。 3、建一个个人公众号，添加到版权信息里，让一些连giyhub都打不开的用户可以找到你。然后用公众号更新，圈粉。用公众号让你产生一点收入，这也算是一种正向反馈。

@dushez 

一年后，特意来谢谢你提供这样的思路，我现在几乎就是按照你说的做的，项目现在几乎可以健康运作下去了。
再次感谢！
