### ISSUE TITLE
机顶盒上使用时出现的问题

### ISSUE THREAD

**Issue by PediyCCDebuger** [hxh19950701/WebViewTvLive#9]
以前一直用 https://github.com/Eanya-Tonic/CCTV_Viewer 的电视浏览器，问题就是每个频道载入都比较慢一点。也是在一个QQ群里看到有人提到广电免费电视这个APP，下载了一个在虚拟机上测试了一下，感觉很不错，一是加载速度要快点，二是台要多一些。但看这个样子不像是原版，就通过查看Main Activity名称，发现是com.vasthread.webviewtv.activity.MainActivity，然后在GitHub上搜用户vasthread，找到这来的。试用了1.2和1.1版本后，有几个问题主要是在创维机顶盒E900V22C上使用时出现的，估计这也是很多电视上存在的问题，希望作者有空能帮忙解决一下：
### 1、在创维E900V22C机顶盒上播放节目时不能全屏。
机顶盒是安卓9系统，原本是看了一些讨论，一直等APP自己安装X5内核，但发现等了很久后，都无法装上。只能在设置中进入TBS调试界面，打算手动安装线上内核。但腾讯的这个X5调试界面在机顶盒上显示是横过来的，且通过遥控器根本无法获取焦点，后来只能通过连接蓝牙鼠标，点击安装线上内核解决此问题。所以在此希望作者可以提供一个类似 CCTV_Viewer 一样的内置X5内核版本，解决在电视盒机顶盒上安装内核的问题。
### 2、获取不了节目列表
启动时发现只有一个央视一套，获取不了节目，原因应该是GitHub上的节目地址被阻挡了。解决方法是按帖子里有人说到的用完整.json 替换了一下 apk 里的 assets/default_playlist.json。后来看作者的源码，节目列表是这样的：
Pair("中央&湖南", "https://raw.githubusercontent.com/hxh19950701/WebViewTvLive/main/app/channels/2.0/%E5%A4%AE%E8%A7%86%26%E6%B9%96%E5%8D%97.json"),
Pair("完整", "https://raw.githubusercontent.com/hxh19950701/WebViewTvLive/main/app/channels/2.0/%E5%AE%8C%E6%95%B4.json"),
希望能加个代理改成类似这样的：
Pair("中央&湖南", "https://ghproxy.net/raw.githubusercontent.com/hxh19950701/WebViewTvLive/main/app/channels/2.0/%E5%A4%AE%E8%A7%86%26%E6%B9%96%E5%8D%97.json"),
Pair("完整", "https://ghproxy.net/raw.githubusercontent.com/hxh19950701/WebViewTvLive/main/app/channels/2.0/%E5%AE%8C%E6%95%B4.json"),
这样就可以正常访问节目列表了。
### 3、播放地方台时卡顿、转圈问题
和前面有个Issues中提到的问题一样，在播放一些地方台上会出现卡顿、转圈现象。同时用 CCTV_Viewer 播放同样的节目则不会出现此类问题。希望作者有空能优化一下。
### 4、建议在关于里加入作者名字或项目地址
可以像tvbox一样，关于里有项目地址。这样也能让更多的人知道，也方便找到正确的发布地址。最后，感谢作者开发的APP，希望能继续更新。

**Comment by hxh19950701** [comment]
谢谢反馈！你所说的问题下个版本2.0都会解决。
但是比较遗憾的是不会再开源了。

**Comment by PediyCCDebuger** [comment]
> 谢谢反馈！你所说的问题下个版本2.0都会解决。 但是比较遗憾的是不会再开源了。

开源难免出现这种被随便修改的问题。后续更新版本发布还在这里吗？

**Comment by hxh19950701** [comment]
项目会一直在的，除非受到某些不可抗原因

**Comment by PediyCCDebuger** [comment]
> 项目会一直在的，除非受到某些不可抗原因

好的，希望能一直更新下去。感谢！

**Comment by PediyCCDebuger** [comment]
测试了1.8版本，1、2、4这几个问题基本解决。
第一条的问题现在进入TBS调试界面，电视上可以正常显示，遥控器可以上下左右操作，虽然看不到焦点，但可以根据上下左右按键次数大概知道在哪里，使用遥控器顺利安装了内核。
第二条的问题现在已不存在，可以正常加载节目列表。
第四条问题也不存在了。
目前有问题的是第三条播放地方台时卡顿、转圈问题。现在的现象是开始的时候会有点卡顿，后面其实播放的时候还行，比较流畅。主要问题是在播放流畅的情况下，经常会出现“正在加载...”这样的文本提示框，这就很影响观看体验。按道理播放没有卡顿的情况下不应该出现这种“正在加载...”的文本提示框。另外这个提示框也太大了点。对比了CCTV_Viewer的加载提示框，CCTV_Viewer就很小。建议把这个加载提示框改小点，不要太起眼，也可以不要居中，可以放在角落里，甚至极端点可以取消掉。当然主要是要解决在没卡顿的情况下出现这个提示框的问题，会很影响观看体验。

**Comment by hxh19950701** [comment]
感谢测试。
第一点我想到了一个更好的办法，“安装线上内核”一般出现在屏幕后1/3的位置。我虚拟点击一下就可以了，想法应该是可行的。
第三点，帮忙详细测试一下。
明明视频正常播放的情况下，弹加载框的，是不是都是央视频的源？
有没有出现“自动全屏后，视频立即卡死，然后弹加载框的”？
另外，帮忙测试一下，遥控器上下键换台功能还正常吗？

**Comment by PediyCCDebuger** [comment]
> ### 第一点我想到了一个更好的办法，“安装线上内核”一般出现在屏幕后1/3的位置。我虚拟点击一下就可以了，想法应该是可行的。

这是指点击进入TBS调试界面后就自动执行安装内核吗？
> ### 明明视频正常播放的情况下，弹加载框的，是不是都是央视频的源？

是的，基本上都是央视频地方台的源会出现这种情况，央视频中央台的很少出现。
> ### 有没有出现“自动全屏后，视频立即卡死，然后弹加载框的”？ 

出现过这种情况，还有一种就是画面卡死，声音正常，还有一种就是一直卡顿，最后直接卡死。但这种情况很少出现。我都怀疑是不是我在TBS调试界面里一通乱点有关。后来我卸载重装了一下，正常安装X5内核，不作其他操作，倒是没再出现这种完全卡死的问题。也不知道是不是后面的测试时间不够，导致未发现。
> ### 另外，帮忙测试一下，遥控器上下键换台功能还正常吗？

不正常，上下键换台不可用。
另外希望能加上按数字键换台的功能，以及能添加自定义导入线上或线下节目列表的功能。

**Comment by PediyCCDebuger** [comment]
刚又打开测试了一下，播放江苏台时出现卡顿，最后卡死，APP直接退出。

**Comment by hxh19950701** [comment]
如果你愿意，且有时间的话，不知能否加入我的测试群？

**Comment by PediyCCDebuger** [comment]
> 如果你愿意，且有时间的话，不知能否加入我的测试群？

可以，是啥群？QQ？

**Comment by hxh19950701** [comment]
> > 如果你愿意，且有时间的话，不知能否加入我的测试群？
> 
> 可以，是啥群？QQ？

见readme

**Comment by virusmaster** [comment]
只能在设置中进入TBS调试界面，打算手动安装线上内核。但腾讯的这个X5调试界面在机顶盒上显示是横过来的，且通过遥控器根本无法获取焦点。 一样难以定位，真心不好搞
